In [1]:

import pandas as pd
best_df=pd.read_csv("results/best.csv")
in_df=pd.read_csv("results/in.csv")
epic_df=pd.read_csv("results/epic.csv")
# best_df["w1m"]=best_df["w1m_2"]
# epic_df["w1m"]=epic_df["w1m_2"]
# in_df["w1m"]=in_df["w1m_2"]

In [2]:
import ast
cols=[]
for col in best_df.columns:
        cols.append(col)
print_table_epic=epic_df.copy()
print_table_epic["model"]="EPiC"
print_table=best_df[cols].copy()
print_table["model"]="MF"

print_table_in=in_df.copy()
print_table_in["model"]="IN"
print_table=pd.concat([print_table_epic,print_table,print_table_in],axis=0)
print_table=print_table.set_index(["name","model"],drop=False)
print_table[cols]

,,Unnamed: 0,name,model,w1m,w1p,w1efp,ngen,ndis,w1m_2,kpd,fpd
name,model,,,,,,,,,,,
q,EPiC,0,q,EPiC,"(0.0005380818426126783, 0.00012904037919663226)","(array([0.00709851, 0.00381849, 0.00058591]), ...","(array([1.35370047e-05, 9.53214904e-06, 1.0009...",-1,-1,"(0.0004591054957508063, 8.649383461895031e-05)","(-1.958591435702317e-07, 1.1785038583775884e-05)","(0.0005341053491202971, 0.00013310076413701875)"
t,EPiC,1,t,EPiC,"(0.0006863091311611832, 7.676010529359234e-05)","(array([0.0065886 , 0.00397579, 0.00058648]), ...","(array([2.95483861e-05, 2.67244292e-05, 2.8335...",-1,-1,"(0.0006501366136218384, 8.982902007380962e-05)","(0.00017356537699408925, 9.713936887636396e-05)","(0.002194345228789496, 0.0001380810601416221)"
g,EPiC,2,g,EPiC,"(0.0004800166228910201, 0.00014511291812883403)","(array([0.00246419, 0.0066544 , 0.00026641]), ...","(array([2.05050649e-05, 1.32874912e-05, 1.4014...",-1,-1,"(0.0005126805953012804, 0.00013984854903972135)","(6.315320947303249e-06, 5.399900267581578e-06)","(0.00042198279169639746, 6.520171428052217e-05)"
q,MF,0,q,MF,"(0.0006573085599490094, 0.0001475383896739996)","(array([0.00081187, 0.00085061, 0.00034754]), ...","(array([1.53677881e-05, 1.06051301e-05, 1.1263...",87136,43040,"(0.0005784311037228062, 0.00013397509370620923)","(-5.390574736363618e-06, 6.596550512017185e-06)","(0.0003837181699465679, 8.110660911092798e-05)"
t,MF,1,t,MF,"(0.0005681532284946354, 9.259398860960902e-05)","(array([6.82228166e-04, 5.52741239e-04, 8.2749...","(array([2.98720053e-05, 2.37120681e-05, 2.4144...",87136,43040,"(0.0004644597127584791, 6.685226158065983e-05)","(-4.130427127657654e-06, 2.065348283618562e-05)","(0.0005334561819876409, 8.582433713424754e-05)"
z,MF,2,z,MF,"(0.00026693750657479315, 2.9128645783081066e-05)","(array([0.00202385, 0.00100433, 0.00016522]), ...","(array([6.46928195e-06, 4.64878340e-06, 4.7991...",87136,43040,"(0.000262949708400072, 3.622250840576647e-05)","(-9.426768714515532e-07, 2.2703698951705984e-06)","(5.9064635287972784e-05, 0.0003701651016867474)"
w,MF,3,w,MF,"(0.0003066636952134232, 2.063523006590899e-05)","(array([0.00056879, 0.00055545, 0.00013604]), ...","(array([7.89449150e-06, 3.43280621e-06, 3.5019...",87136,43040,"(0.00030046052956580316, 4.129573567643267e-05)","(1.481378691492452e-06, 1.9265747277891207e-06)","(0.00014494313364155835, 0.0003956571505347969)"
g,MF,4,g,MF,"(0.0005488529260992856, 0.00014579296096439977)","(array([0.00284739, 0.00207062, 0.0002425 ]), ...","(array([1.44532061e-05, 1.24974265e-05, 1.2710...",87136,43040,"(0.00044112813731730303, 0.00012521975185344315)","(-4.9819993914734795e-06, 3.252280861391953e-06)","(0.00013712365856081535, 4.6620247770693574e-05)"
q,IN,0,q,IN,"(0.0005261134101585301, 0.00010012642784270297)","(array([0.00050411, 0.00051531, 0.00013132]), ...","(array([1.07512628e-05, 8.21342078e-06, 8.5567...",-1,-1,"(0.0003667746383084425, 0.00011456124388040276)","(-8.267994342503471e-07, 1.6582255112136397e-05)","(0.00032532692210288387, 0.0001928617754240179)"
t,IN,1,t,IN,"(0.00042199122771594493, 9.141194703358981e-05)","(array([5.49865667e-04, 4.06908556e-04, 8.7960...","(array([1.59779195e-05, 1.43777483e-05, 1.5071...",-1,-1,"(0.000290375192064777, 0.00010277509631373942)","(-6.759204400186292e-06, 2.1565146969005353e-05)","(0.00011735291903745956, 5.551673946689224e-05)"
z,IN,2,z,IN,"(0.0001840437972612268, 2.5516166578243933e-05)","(array([0.00041032, 0.00042548, 0.00014651]), ...","(array([3.21853591e-06, 1.86999660e-06, 2.0119...",-1,-1,"(0.00011960538567241293, 2.2198301154371216e-05)","(2.997757646561183e-07, 2.2347570059727534e-06)","(0.00015668038113774587, 0.00013200194657570643)"
w,IN,3,w,IN,"(0.00017734276394184325, 4.938023437908109e-05)","(array([0.00036069, 0.00037245, 0.00011996]), ...","(array([2.57189868e-06, 1.48889967e-06, 1.6054...",-1,-1,"(0.00011200469372068126, 3.7880148503942247e-05)","(-2.9822484570729557e-07, 1.149721461532027e-06)","(0.00014026648906651193, 0.00012327349417574028)"
g,IN,4,g,IN,"(0.0005511342526046544, 0.00017080451363288236)","(array([4.19700131e-04, 5.11470772e-04, 4.5423...","(array([1.23928847e-05, 9.47220722e-06, 9.5851...",-1,-1,"(0.000489244155655612, 0.00017263899683943735)","(-6.7302342801056625e-06, 1.2841585572583859e-05)","(0.0003207750266109, 7.754046585598929e-05)"

In [3]:
import numpy as np
for col in ["w1m","w1p","w1efp","kpd","fpd"]:

        print_table[col]=print_table[col].str.replace("array","").apply(ast.literal_eval)

from tkinter import W
import pandas as pd
from numpy import array
import ast

def format_mean_sd(mean, sd,efp=False):
    """round mean and standard deviation to most significant digit of sd and apply latex formatting"""
    decimals = -int(np.floor(np.log10(sd)))+int(efp)+1
    decimals -= int((sd * 10 ** decimals) >= 9.5)
    if decimals < 0:
        ten_to = 10 ** (-decimals)
        if mean > ten_to:
            mean = ten_to * (mean // ten_to)
        else:
            mean_ten_to = 10 ** np.floor(np.log10(mean))
            mean = mean_ten_to * (mean // mean_ten_to)
        sd = ten_to * (sd // ten_to)
        decimals = 0

    if mean >= 1e3 and sd >= 1e3:
        mean = np.round(mean * 1e-3)
        sd = np.round(sd * 1e-3)
        return f"${mean:.{decimals}f}$k $\\pm {sd:.{decimals}f}$k"
   
    else:
        return f"${mean:.{decimals}f} \\pm {sd:.{decimals}f}$"

# print_table.index=["t"]#"q"

def weighted_mean(x):
    x,w=np.array(x[0]),np.array(x[1]) 
    weights=1/w**2
    return np.sum(x*weights)/np.sum(weights)
def weighted_std(x):
    x,w=np.array(x[1]),np.array(x[1])
    weights=1/w**2
    return np.sum(x*weights)/np.sum(weights)

print_table["pmm"]=print_table["w1m"].apply(lambda x:x).apply(weighted_std)
print_table["w1m"]=print_table["w1m"].apply(lambda x:x).apply(weighted_mean)
print_table["pmp"]=print_table["w1p"].apply(lambda x:x).apply(weighted_std)
print_table["w1p"]=print_table["w1p"].apply(lambda x:x).apply(weighted_mean)
print_table["pme"]=print_table["w1efp"].apply(lambda x:x).apply(weighted_std)
print_table["w1efp"]=print_table["w1efp"].apply(lambda x:x).apply(weighted_mean)
print(print_table["pme"])
print_table["fpd_std"]=print_table["fpd"].apply(lambda x:x[1]).apply(np.mean)
print_table["fpd"]=print_table["fpd"].apply(lambda x:x[0]).apply(np.mean)
print_table["kpd_std"]=print_table["kpd"].apply(lambda x:x[1]).apply(np.mean)
print_table["kpd"]=print_table["kpd"].apply(lambda x:x[0]).apply(np.mean)

cols=["w1m","w1efp","w1m","pmm","pme","pmp"]


# print_table=print_table[["w1m","w1p","w1efp","fpnd","cov","mmd","pmm","pmp","pme","model"]]

print_table.loc[:,"w1m"]*=1000
print_table.loc[:,"w1p"]*=1000
print_table.loc[:,"w1efp"]*=100000
print_table.loc[:,"pmm"]*=1000
print_table.loc[:,"pmp"]*=1000
print_table.loc[:,"pme"]*=100000
print_table.loc[:,"fpd"]*=10000
print_table.loc[:,"kpd"]*=10000
print_table.loc[:,"fpd_std"]*=10000
print_table.loc[:,"kpd_std"]*=10000


index=["q","g","t","w","z"]

print_table.loc[:,"w1m"]=print_table.apply(lambda x:format_mean_sd(float(x["w1m"]),float(x["pmm"])),axis=1)
print_table.loc[:,"w1efp"]=print_table.apply(lambda x:format_mean_sd(float(x["w1efp"]),float(x["pme"]),efp=True),axis=1)
print_table.loc[:,"w1p"]=print_table.apply(lambda x:format_mean_sd(float(x["w1p"]),float(x["pmp"])),axis=1)
print_table.loc[:,"kpd"]=print_table.apply(lambda x:format_mean_sd(float(x["kpd"]),float(x["kpd_std"])),axis=1)
print_table.loc[:,"fpd"]=print_table.apply(lambda x:format_mean_sd(float(x["fpd"]),float(x["fpd_std"])),axis=1)


# print_table.loc[:,"cov"]=print_table.loc[:,"cov"].astype(float).map('{:.2f}'.format)

# print_table.loc[:,"mmd"]=print_table.loc[:,"mmd"].astype(float).map('{:.3f}'.format)
print_table.loc[:,"pmm"]=print_table.loc[:,"pmm"].astype(float).map('{:,.2f}'.format)

print_table.loc[:,"pmp"]=print_table.loc[:,"pmp"].astype(float).map('{:,.2f}'.format)

print_table.loc[:,"pme"]=print_table.loc[:,"pme"].astype(float).map('{:,.2f}'.format)

# print_table.loc[:,"w1m"]="$"+print_table["w1m"].map(str)+"\pm"+print_table["pmm"].map(str)+"$"
# print_table.loc[:,"w1p"]="$"+print_table["w1p"].map(str)+"\pm"+print_table["pmp"].map(str)+"$"
# print_table.loc[:,"w1efp"]="$"+print_table["w1efp"].map(str)+"\pm"+print_table["pme"].map(str)+"$"
# print_table.loc[:,"kpd"]="$"+print_table["kpd"].map(str)+"\pm"+print_table["kpd_std"].map(str)+"$"
# print_table.loc[:,"fpd"]="$"+print_table["fpd"].map(str)+"\pm"+print_table["fpd_std"].map(str)+"$"

print_table=print_table.loc[index,:]
print_table

name  model
q     EPiC     1.632870e-06
t     EPiC     3.851669e-06
g     EPiC     1.373094e-06
q     MF       1.357669e-06
t     MF       6.422428e-06
z     MF       6.943246e-07
w     MF       3.996572e-07
g     MF       1.291517e-06
q     IN       1.602081e-06
t     IN       3.212354e-06
z     IN       4.192232e-07
w     IN       2.141353e-07
g     IN       2.436764e-06
Name: pme, dtype: float64

            Unnamed: 0 name model              w1m                w1p
name model
q    EPiC            0    q  EPiC    $0.5 \pm 0.1$    $1.25 \pm 0.09$  \
     MF              0    q    MF    $0.7 \pm 0.1$    $0.37 \pm 0.05$
     IN              0    q    IN    $0.5 \pm 0.1$    $0.15 \pm 0.04$
g    EPiC            2    g  EPiC    $0.5 \pm 0.1$    $1.13 \pm 0.04$
     MF              4    g    MF    $0.5 \pm 0.1$    $0.27 \pm 0.02$
     IN              4    g    IN    $0.6 \pm 0.2$  $0.048 \pm 0.009$
t    EPiC            1    t  EPiC  $0.69 \pm 0.08$    $0.65 \pm 0.03$
     MF              1    t    MF  $0.57 \pm 0.09$    $0.10 \pm 0.02$
     IN              1    t    IN  $0.42 \pm 0.09$    $0.12 \pm 0.04$
w    MF              3    w    MF  $0.31 \pm 0.02$    $0.20 \pm 0.04$
     IN              3    w    IN  $0.18 \pm 0.05$    $0.14 \pm 0.04$
z    MF              2    z    MF  $0.27 \pm 0.03$    $0.23 \pm 0.04$
     IN              2    z    IN  $0.18 \pm 0.03$    $0.24 \pm 0.07$

                        w1efp   ngen   ndis
name model
q    EPiC     $0.81 \pm 0.16$     -1     -1  \
     MF       $0.82 \pm 0.14$  87136  43040
     IN       $0.59 \pm 0.16$     -1     -1
g    EPiC     $0.93 \pm 0.14$     -1     -1
     MF       $1.12 \pm 0.13$  87136  43040
     IN       $0.79 \pm 0.24$     -1     -1
t    EPiC     $2.67 \pm 0.39$     -1     -1
     MF       $2.12 \pm 0.64$  87136  43040
     IN       $1.22 \pm 0.32$     -1     -1
w    MF     $0.284 \pm 0.040$  87136  43040
     IN     $0.136 \pm 0.021$     -1     -1
z    MF     $0.373 \pm 0.069$  87136  43040
     IN     $0.152 \pm 0.042$     -1     -1

                                                       w1m_2
name model
q    EPiC     (0.0004591054957508063, 8.649383461895031e-05)  \
     MF      (0.0005784311037228062, 0.00013397509370620923)
     IN      (0.0003667746383084425, 0.00011456124388040276)
g    EPiC    (0.0005126805953012804, 0.00013984854903972135)
     MF     (0.00044112813731730303, 0.00012521975185344315)
     IN       (0.000489244155655612, 0.00017263899683943735)
t    EPiC     (0.0006501366136218384, 8.982902007380962e-05)
     MF       (0.0004644597127584791, 6.685226158065983e-05)
     IN       (0.000290375192064777, 0.00010277509631373942)
w    MF      (0.00030046052956580316, 4.129573567643267e-05)
     IN     (0.00011200469372068126, 3.7880148503942247e-05)
z    MF        (0.000262949708400072, 3.622250840576647e-05)
     IN     (0.00011960538567241293, 2.2198301154371216e-05)

                         kpd            fpd   pmm   pmp   pme   fpd_std
name model
q    EPiC     $-0.0 \pm 0.1$      $5 \pm 1$  0.13  0.09  0.16  1.331008  \
     MF     $-0.05 \pm 0.07$  $3.8 \pm 0.8$  0.15  0.05  0.14  0.811066
     IN       $-0.0 \pm 0.2$      $3 \pm 2$  0.10  0.04  0.16  1.928618
g    EPiC    $0.06 \pm 0.05$  $4.2 \pm 0.7$  0.15  0.04  0.14  0.652017
     MF     $-0.05 \pm 0.03$  $1.4 \pm 0.5$  0.15  0.02  0.13  0.466202
     IN       $-0.1 \pm 0.1$  $3.2 \pm 0.8$  0.17  0.01  0.24  0.775405
t    EPiC      $1.7 \pm 1.0$     $22 \pm 1$  0.08  0.03  0.39  1.380811
     MF       $-0.0 \pm 0.2$  $5.3 \pm 0.9$  0.09  0.02  0.64  0.858243
     IN       $-0.1 \pm 0.2$  $1.2 \pm 0.6$  0.09  0.04  0.32  0.555167
w    MF      $0.01 \pm 0.02$      $1 \pm 4$  0.02  0.04  0.04  3.956572
     IN     $-0.00 \pm 0.01$      $1 \pm 1$  0.05  0.04  0.02  1.232735
z    MF     $-0.01 \pm 0.02$      $1 \pm 4$  0.03  0.04  0.07  3.701651
     IN      $0.00 \pm 0.02$      $2 \pm 1$  0.03  0.07  0.04  1.320019

             kpd_std
name model
q    EPiC   0.117850
     MF     0.065966
     IN     0.165823
g    EPiC   0.053999
     MF     0.032523
     IN     0.128416
t    EPiC   0.971394
     MF     0.206535
     IN     0.215651
w    MF     0.019266
     IN     0.011497
z    MF     0.022704
     IN     0.022348

In [57]:


tex=r"""\begin{table}[]
    \centering
    \begin{tabular}{ll|lllll}Jet Class & Model & $W_1^M (\times 10^{3})$ & $W_1^P
(\times 10^{3})$ & $W_1^{EFP}(\times 10^{5})$ &KPD (\times 10^{4})&FPD(\times 10^{4})\\\cline{1-7}
\cline{1-7}"""
for p in ["q","g","t","w","z"]:
    temp_full=print_table[print_table["name"]==p].copy()
    temp=temp_full[temp_full["model"]!="IN"]

    for col in ["w1m","w1p","w1efp","kpd","fpd"]:
        



        temp_vals=temp.loc[temp["model"]!="IN",col].astype(str).str.replace("$","").str.split("\\").str[0].astype(float)
        min_unc=temp.loc[temp["model"]!="IN",col].astype(str).str.replace("$","").str.split("pm").str[1].astype(float).min()
        min_range = (temp_vals.min() - min_unc, temp_vals.min() + min_unc)
        
        compatible = (temp_vals >= min_range[0]) & (temp_vals <= min_range[1])
        compatible[temp_vals.argmin()]=False
        if not compatible.any():
            temp_full.loc[:,col].values[temp_vals.argmin()]="$\mathbf{"+temp_full.loc[:,col].values[temp_vals.argmin()].replace("$","")+"}$"

    temp=temp_full[["model","w1m","w1p","w1efp","kpd","fpd"]]

    temp.columns=["model","$W_1^M (\times 10^{3})$","$W_1^P (\times 10^{3})$","$W_1^{EFP}(\times 10^{5})$","FPD","KPD"]
    text=temp.to_latex(index=False,escape=False)
    parton="Gluon" if p=="g" else "Light Quark" if p=="q" else "Top Quark" if p=="t" else "W" if p=="w" else "Z"
    k=1 if p in ["w","z"] else 2
    tex+="\multirow{"+str(k)+"}{*}{"+parton+"} & "+text.split("KPD \\\\")[1].split("\\bottomrule")[0].replace("\\\\","\\\\&").replace("\\midrule","").replace("MP_LFC","MP\_LFC").replace("  ","")[:-2]+"\cline{1-7}" 
    tex+="\n"


tex+="""  \end{tabular}

\end{table}"""
print(tex)

\begin{table}[]
    \centering
    \begin{tabular}{ll|lllll}Jet Class & Model & $W_1^M (\times 10^{3})$ & $W_1^P
(\times 10^{3})$ & $W_1^{EFP}(\times 10^{5})$ &KPD (\times 10^{4})&FPD(\times 10^{4})\\\cline{1-7}
\cline{1-7}\multirow{2}{*}{Light Quark} &

EPiC & $\mathbf{0.5 \pm 0.1}$ & $1.25 \pm 0.09$ & $0.81 \pm 0.16$ & $-0.0 \pm 0.1$ & $5 \pm 1$ \\&
MF & $0.7 \pm 0.1$ & $\mathbf{0.37 \pm 0.05}$ & $0.82 \pm 0.14$ & $-0.05 \pm 0.07$ & $\mathbf{3.8 \pm 0.8}$ \\&
IN & $0.5 \pm 0.1$ & $0.15 \pm 0.04$ & $0.59 \pm 0.16$ & $-0.0 \pm 0.2$ & $3 \pm 2$ \\\cline{1-7}
\multirow{2}{*}{Gluon} &

EPiC & $0.5 \pm 0.1$ & $1.13 \pm 0.04$ & $\mathbf{0.93 \pm 0.14}$ & $0.06 \pm 0.05$ & $4.2 \pm 0.7$ \\&
MF & $0.5 \pm 0.1$ & $\mathbf{0.27 \pm 0.02}$ & $1.12 \pm 0.13$ & $\mathbf{-0.05 \pm 0.03}$ & $\mathbf{1.4 \pm 0.5}$ \\&
IN & $0.6 \pm 0.2$ & $0.048 \pm 0.009$ & $0.79 \pm 0.24$ & $-0.1 \pm 0.1$ & $3.2 \pm 0.8$ \\\cline{1-7}
\multirow{2}{*}{Top Quark} &

EPiC & $0.69 \pm 0.08$ & $0.65 \pm 0.03$ & $2.67 \pm 0.39$ & $1.7 \pm 1.0$ & $22 \pm 1$ \\&
MF & $\mathbf{0.57 \pm 0.09}$ & $\mathbf{0.10 \pm 0.02}$ & $\mathbf{2.12 \pm 0.64}$ & $\mathbf{-0.0 \pm 0.2}$ & $\mathbf{5.3 \pm 0.9}$ \\&
IN & $0.42 \pm 0.09$ & $0.12 \pm 0.04$ & $1.22 \pm 0.32$ & $-0.1 \pm 0.2$ & $1.2 \pm 0.6$ \\\cline{1-7}
\multirow{1}{*}{W} &

MF & $\mathbf{0.31 \pm 0.02}$ & $\mathbf{0.20 \pm 0.04}$ & $\mathbf{0.284 \pm 0.040}$ & $\mathbf{0.01 \pm 0.02}$ & $\mathbf{1 \pm 4}$ \\&
IN & $0.18 \pm 0.05$ & $0.14 \pm 0.04$ & $0.136 \pm 0.021$ & $-0.00 \pm 0.01$ & $1 \pm 1$ \\\cline{1-7}
\multirow{1}{*}{Z} &

MF & $\mathbf{0.27 \pm 0.03}$ & $\mathbf{0.23 \pm 0.04}$ & $\mathbf{0.373 \pm 0.069}$ & $\mathbf{-0.01 \pm 0.02}$ & $\mathbf{1 \pm 4}$ \\&
IN & $0.18 \pm 0.03$ & $0.24 \pm 0.07$ & $0.152 \pm 0.042$ & $0.00 \pm 0.02$ & $2 \pm 1$ \\\cline{1-7}
  \end{tabular}

\end{table}

In [41]:
temp_vals.argmin(),col

(0, 'w1m')

'$0.5 \\pm 0.1$'

In [33]:
temp_vals.argmin()

0

In [13]:
temp

            Unnamed: 0 name model            w1m            w1p
name model
g    EPiC            2    g  EPiC  $0.5 \pm 0.1$  $3.1 \pm 0.1$  \
     MF              4    g    MF  $0.6 \pm 0.1$  $0.6 \pm 0.1$

                    w1efp   ngen   ndis
name model
g    EPiC   $1.3 \pm 0.3$     -1     -1  \
     MF         $2 \pm 1$  87136  43040

                                                       w1m_2
name model
g    EPiC    (0.0005126805953012804, 0.00013984854903972135)  \
     MF     (0.00047822019005218055, 0.00015324029982696628)

                         kpd                  fpd   pmm   pmp   pme
name model
g    EPiC    $0.06 \pm 0.05$        $4.2 \pm 0.7$  0.15  0.12  0.32  \
     MF     $-0.06 \pm 0.03$  $6000$k $\pm 1000$k  0.10  0.11  1.41

                 fpd_std   kpd_std
name model
g    EPiC   6.520171e-01  0.053999
     MF     1.961935e+06  0.025613